# Generated by Django 5.1.1 on 2024-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hooks_content', models.FileField(upload_to='hooks_content/')),
                ('google_sheets_link', models.URLField(max_length=1000)),
                ('eleven_labs_api_key', models.CharField(max_length=1000)),
                ('voice_id', models.CharField(max_length=1000)),
                ('task_id', models.CharField(max_length=1000, unique=True)),
                ('main_box_color', models.CharField(max_length=7)),
                ('font_color', models.CharField(max_length=7)),
                ('parallel_processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
